### ISSUE TITLE
Regarding HDMI-CEC

### ISSUE THREAD

**Issue by qokrb2t** [kerta1n/tank-convert#1]
Would you like to update the readme with how a tv remote can be used to control the android-tv?
I had issues with making the firetvstick's remote working & could've saved a lot of time if i knew about it earlier

Its just a two step process & will help save the spending on  the micro-usb-y-splitter-otg
1. Findout what your tv manufacturer calls hdmi-cec. Some help is available at https://en.m.wikipedia.org/wiki/Consumer_Electronics_Control
2. Turn it on in your tv using tv's remote

**Comment by kerta1n** [comment]
Apologies for seeing this so late, but I didn't know this ROM accepted CEC controls. Will add this, thanks
