### ISSUE TITLE
BT on los 12.1 (5.1) Tank

### ISSUE THREAD

**Issue by dinzysl** [kerta1n/tank-convert#2]
I can't connect Bluetooth devices like an external speaker or Xbox controller to Firestick. The only device I can connect is the Firestick remote + my device is rooted w magisk, Is there a workaround or fix? If so it'll be much appreciated :) as there ain't any major issues in this rom

**Comment by kerta1n** [comment]
> I can't connect Bluetooth devices like an external speaker or Xbox controller to Firestick. The only device I can connect is the Firestick remote + my device is rooted w magisk, Is there a workaround or fix? If so it'll be much appreciated :) as there ain't any major issues in this rom 

Sorry for replying so late 😄, I have a feeling that magisk may be the problem. I was able to connect a Vizio sound bar and I do not have magisk installed. You'd be better off asking R0rt1z in an XDA forum, as he was the one who mainly developed the image

**Comment by kerta1n** [comment]
Closing with inactivity
