### ISSUE TITLE
update documentation: ADB over USB is usable with some configuration

### ISSUE THREAD

**Issue by That1LoserGuy** [kerta1n/tank-convert#3]
Credits to this post: https://stackoverflow.com/questions/30178911/how-to-authorize-and-accept-adb-rsa-key-with-broken-touch-screen-on-android

ADB over USB can be used if you first go into TWRP and copy over your devices ADB RSA key.

If you are using macOS (or any Linux distro):

    1. Reboot your phone into recovery mode.

    2. Connect it to your computer.

    3. Open the terminal and type:

     cd ~/.android
     adb push adbkey.pub /data/misc/adb/adb_keys

   4. All done! Just adb shell reboot and feel the power!

*For Windows 10, .android directory is located in your the base of your C:\User\user_name directory.

**Comment by kerta1n** [comment]
Added in abee8f3d227d465abdfeb8f58e88d6dd830e2b06 . Thanks for the addition!
